import 'dotenv/config';
import { db } from './db/index.js';
import bcrypt from 'bcryptjs';
import {
  users,
  workspaces,
  workspaceMembers,
  projects,
  projectMembers,
  tasks,
  invitations,
  comments,
  clients,
  clientIntakes,
} from './db/schema.js';

const run = async () => {
  await db.delete(comments);
  await db.delete(tasks);
  await db.delete(projectMembers);
  await db.delete(invitations);
  await db.delete(projects);
  await db.delete(clientIntakes);
  await db.delete(clients);
  await db.delete(workspaceMembers);
  await db.delete(workspaces);
  await db.delete(users);

  const adminPasswordHash = await bcrypt.hash('Password123', 10);
  const memberPasswordHash = await bcrypt.hash('Password123', 10);
  const now = new Date();
  const daysAgo = (days) => new Date(now.getTime() - days * 86400000);

  await db.insert(users).values([
    {
      id: 'user_admin',
      name: 'Admin',
      email: 'admin@admin.com',
      image: null,
      role: 'ADMIN',
      password_hash: adminPasswordHash,
    },
    {
      id: 'user_alice',
      name: 'Alice Johnson',
      email: 'alice@orbit.io',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
    {
      id: 'user_bob',
      name: 'Bob Carter',
      email: 'bob@pulse.io',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
    {
      id: 'user_charles',
      name: 'Charles Nguyen',
      email: 'charles@northridge.co',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
    {
      id: 'user_dana',
      name: 'Dana Patel',
      email: 'dana@orbit.io',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
    {
      id: 'user_elliot',
      name: 'Elliot Moore',
      email: 'elliot@pulse.io',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
    {
      id: 'user_farah',
      name: 'Farah Ali',
      email: 'farah@northridge.co',
      image: null,
      role: 'USER',
      password_hash: memberPasswordHash,
    },
  ]);

  await db.insert(workspaces).values([
    {
      id: 'org_orbit',
      name: 'Orbit Studio',
      slug: 'orbit-studio',
      description: 'Product design and growth experiments.',
      settings: { theme: 'ocean' },
      ownerId: 'user_admin',
      image_url: null,
    },
    {
      id: 'org_pulse',
      name: 'Pulse Operations',
      slug: 'pulse-ops',
      description: 'Operations, support, and internal tooling.',
      settings: { theme: 'sunset' },
      ownerId: 'user_alice',
      image_url: null,
    },
    {
      id: 'org_north',
      name: 'Northridge Agency',
      slug: 'northridge-agency',
      description: 'Client delivery across web and mobile.',
      settings: { theme: 'forest' },
      ownerId: 'user_bob',
      image_url: null,
    },
  ]);

  await db.insert(workspaceMembers).values([
    {
      id: 'wm_orbit_admin',
      workspaceId: 'org_orbit',
      userId: 'user_admin',
      role: 'ADMIN',
      message: '',
    },
    {
      id: 'wm_orbit_alice',
      workspaceId: 'org_orbit',
      userId: 'user_alice',
      role: 'MEMBER',
      message: 'Design lead',
    },
    {
      id: 'wm_orbit_dana',
      workspaceId: 'org_orbit',
      userId: 'user_dana',
      role: 'MEMBER',
      message: 'Project manager',
    },
    {
      id: 'wm_pulse_alice',
      workspaceId: 'org_pulse',
      userId: 'user_alice',
      role: 'ADMIN',
      message: '',
    },
    {
      id: 'wm_pulse_bob',
      workspaceId: 'org_pulse',
      userId: 'user_bob',
      role: 'MEMBER',
      message: '',
    },
    {
      id: 'wm_pulse_elliot',
      workspaceId: 'org_pulse',
      userId: 'user_elliot',
      role: 'MEMBER',
      message: 'Support',
    },
    {
      id: 'wm_north_bob',
      workspaceId: 'org_north',
      userId: 'user_bob',
      role: 'ADMIN',
      message: '',
    },
    {
      id: 'wm_north_charles',
      workspaceId: 'org_north',
      userId: 'user_charles',
      role: 'MEMBER',
      message: 'Engineer',
    },
    {
      id: 'wm_north_farah',
      workspaceId: 'org_north',
      userId: 'user_farah',
      role: 'MEMBER',
      message: 'QA',
    },
  ]);

  await db.insert(clients).values([
    {
      id: 'client_aurora',
      workspaceId: 'org_orbit',
      name: 'Aurora Health',
      company: 'Aurora Health',
      email: 'ops@aurorahealth.com',
      phone: '+1 415 555 1201',
      website: 'https://aurorahealth.com',
      industry: 'Healthcare',
      status: 'ACTIVE',
      details: {
        source: 'MANUAL',
        contactName: 'Maria Sanchez',
        goals: 'Patient onboarding redesign',
        budget: '$25k',
        timeline: '6 weeks',
        targetAudience: 'Patients and caregivers',
        brandGuidelines: 'Strict HIPAA compliance',
        competitors: 'Careplus, Medigo',
        successMetrics: 'Reduced drop-off by 20%',
        notes: 'Accessibility is critical.',
      },
      updatedAt: now,
    },
    {
      id: 'client_lumen',
      workspaceId: 'org_orbit',
      name: 'Lumen Labs',
      company: 'Lumen Labs',
      email: 'hello@lumenlabs.io',
      phone: '+1 415 555 2109',
      website: 'https://lumenlabs.io',
      industry: 'Biotech',
      status: 'ACTIVE',
      details: {
        source: 'INTAKE',
        intakeId: 'intake_lumen',
        goals: 'Investor-ready product story',
        budget: '$18k',
        timeline: '4 weeks',
        targetAudience: 'Investors and researchers',
        brandGuidelines: 'Use existing deck palette',
        competitors: 'GeneCore',
        successMetrics: '3 investor demos booked',
        notes: 'Need case study layout.',
      },
      updatedAt: now,
    },
    {
      id: 'client_pulsecare',
      workspaceId: 'org_pulse',
      name: 'Pulse Care',
      company: 'Pulse Care',
      email: 'support@pulsecare.com',
      phone: '+1 646 555 7782',
      website: 'https://pulsecare.com',
      industry: 'Wellness',
      status: 'ACTIVE',
      details: {
        source: 'MANUAL',
        contactName: 'Kevin Lee',
        goals: 'Automate onboarding flows',
        budget: '$12k',
        timeline: '3 weeks',
        targetAudience: 'New customers',
        brandGuidelines: 'Friendly, energetic',
        competitors: 'FreshHealth',
        successMetrics: 'Reduce tickets by 30%',
        notes: 'Include FAQ templates.',
      },
      updatedAt: now,
    },
    {
      id: 'client_summit',
      workspaceId: 'org_north',
      name: 'Summit Logistics',
      company: 'Summit Logistics',
      email: 'dispatch@summitlogistics.com',
      phone: '+1 212 555 9011',
      website: 'https://summitlogistics.com',
      industry: 'Logistics',
      status: 'ACTIVE',
      details: {
        source: 'INTAKE',
        intakeId: 'intake_summit',
        goals: 'Shipment tracking portal',
        budget: '$30k',
        timeline: '8 weeks',
        targetAudience: 'Operations managers',
        brandGuidelines: 'Clean, industrial',
        competitors: 'TrackFleet',
        successMetrics: 'Cut phone inquiries by 40%',
        notes: 'Support mobile scanners.',
      },
      updatedAt: now,
    },
    {
      id: 'client_nova',
      workspaceId: 'org_north',
      name: 'Nova Retail',
      company: 'Nova Retail',
      email: 'retail@novastores.com',
      phone: '+1 312 555 4411',
      website: 'https://novastores.com',
      industry: 'Retail',
      status: 'ACTIVE',
      details: {
        source: 'MANUAL',
        contactName: 'Sharon Kim',
        goals: 'Mobile POS redesign',
        budget: '$22k',
        timeline: '5 weeks',
        targetAudience: 'Store associates',
        brandGuidelines: 'High contrast, fast',
        competitors: 'QuickPOS',
        successMetrics: 'Reduce checkout time by 15%',
        notes: 'Offline mode required.',
      },
      updatedAt: now,
    },
  ]);

  await db.insert(clientIntakes).values([
    {
      id: 'intake_lumen',
      workspaceId: 'org_orbit',
      clientId: 'client_lumen',
      token: 'token_lumen',
      status: 'SUBMITTED',
      payload: {
        clientName: 'Lumen Labs',
        company: 'Lumen Labs',
        email: 'hello@lumenlabs.io',
        phone: '+1 415 555 2109',
        website: 'https://lumenlabs.io',
        industry: 'Biotech',
        projectName: 'Investor Storytelling Site',
        goals: 'Tell research story and book demos',
        budget: '$18k',
        timeline: '4 weeks',
        targetAudience: 'Investors and scientists',
        brandGuidelines: 'Use deck palette',
        competitors: 'GeneCore',
        successMetrics: '3 investor demos booked',
        notes: 'Needs case study layout.',
      },
      expiresAt: daysAgo(-10),
      submittedAt: daysAgo(4),
      createdAt: daysAgo(12),
    },
    {
      id: 'intake_summit',
      workspaceId: 'org_north',
      clientId: 'client_summit',
      token: 'token_summit',
      status: 'SUBMITTED',
      payload: {
        clientName: 'Summit Logistics',
        company: 'Summit Logistics',
        email: 'dispatch@summitlogistics.com',
        phone: '+1 212 555 9011',
        website: 'https://summitlogistics.com',
        industry: 'Logistics',
        projectName: 'Shipment Tracking Portal',
        goals: 'Provide real-time delivery updates',
        budget: '$30k',
        timeline: '8 weeks',
        targetAudience: 'Ops managers',
        brandGuidelines: 'Industrial and clear',
        competitors: 'TrackFleet',
        successMetrics: 'Cut phone inquiries by 40%',
        notes: 'Mobile scanner support needed.',
      },
      expiresAt: daysAgo(-7),
      submittedAt: daysAgo(3),
      createdAt: daysAgo(9),
    },
    {
      id: 'intake_open_orbit',
      workspaceId: 'org_orbit',
      clientId: null,
      token: 'token_orbit_open',
      status: 'OPEN',
      payload: {},
      expiresAt: daysAgo(-3),
      submittedAt: null,
      createdAt: daysAgo(1),
    },
  ]);

  await db.insert(projects).values([
    {
      id: 'proj_aurora',
      workspaceId: 'org_orbit',
      clientId: 'client_aurora',
      name: 'Aurora Patient Onboarding',
      description: 'Redesign onboarding journey and reduce drop-offs.',
      priority: 'HIGH',
      status: 'ACTIVE',
      start_date: daysAgo(20),
      end_date: daysAgo(-20),
      team_lead: 'user_dana',
      progress: 45,
      updatedAt: now,
    },
    {
      id: 'proj_lumen',
      workspaceId: 'org_orbit',
      clientId: 'client_lumen',
      name: 'Lumen Investor Site',
      description: 'Landing site and narrative deck support.',
      priority: 'MEDIUM',
      status: 'PLANNING',
      start_date: daysAgo(3),
      end_date: daysAgo(-25),
      team_lead: 'user_alice',
      progress: 10,
      updatedAt: now,
    },
    {
      id: 'proj_pulsecare',
      workspaceId: 'org_pulse',
      clientId: 'client_pulsecare',
      name: 'Pulse Care Automation',
      description: 'Automate onboarding and support flows.',
      priority: 'HIGH',
      status: 'ACTIVE',
      start_date: daysAgo(12),
      end_date: daysAgo(-18),
      team_lead: 'user_bob',
      progress: 60,
      updatedAt: now,
    },
    {
      id: 'proj_summit',
      workspaceId: 'org_north',
      clientId: 'client_summit',
      name: 'Summit Tracking Portal',
      description: 'Client portal with live tracking and alerts.',
      priority: 'HIGH',
      status: 'ACTIVE',
      start_date: daysAgo(15),
      end_date: daysAgo(-30),
      team_lead: 'user_charles',
      progress: 35,
      updatedAt: now,
    },
    {
      id: 'proj_nova',
      workspaceId: 'org_north',
      clientId: 'client_nova',
      name: 'Nova POS Redesign',
      description: 'Revamp mobile POS for store teams.',
      priority: 'MEDIUM',
      status: 'ON_HOLD',
      start_date: daysAgo(8),
      end_date: daysAgo(-15),
      team_lead: 'user_farah',
      progress: 20,
      updatedAt: now,
    },
  ]);

  await db.insert(projectMembers).values([
    { id: 'pm_aurora_admin', projectId: 'proj_aurora', userId: 'user_admin' },
    { id: 'pm_aurora_dana', projectId: 'proj_aurora', userId: 'user_dana' },
    { id: 'pm_aurora_alice', projectId: 'proj_aurora', userId: 'user_alice' },
    { id: 'pm_lumen_admin', projectId: 'proj_lumen', userId: 'user_admin' },
    { id: 'pm_lumen_alice', projectId: 'proj_lumen', userId: 'user_alice' },
    { id: 'pm_pulse_bob', projectId: 'proj_pulsecare', userId: 'user_bob' },
    {
      id: 'pm_pulse_elliot',
      projectId: 'proj_pulsecare',
      userId: 'user_elliot',
    },
    { id: 'pm_summit_bob', projectId: 'proj_summit', userId: 'user_bob' },
    {
      id: 'pm_summit_charles',
      projectId: 'proj_summit',
      userId: 'user_charles',
    },
    { id: 'pm_summit_farah', projectId: 'proj_summit', userId: 'user_farah' },
    { id: 'pm_nova_charles', projectId: 'proj_nova', userId: 'user_charles' },
    { id: 'pm_nova_farah', projectId: 'proj_nova', userId: 'user_farah' },
  ]);

  await db.insert(tasks).values([
    {
      id: 'task_aurora_1',
      projectId: 'proj_aurora',
      title: 'Map onboarding journey',
      description: 'Audit current steps and drop-off points.',
      status: 'IN_PROGRESS',
      type: 'FEATURE',
      priority: 'HIGH',
      assigneeId: 'user_dana',
      due_date: daysAgo(-7),
      updatedAt: now,
    },
    {
      id: 'task_aurora_2',
      projectId: 'proj_aurora',
      title: 'Design new intake screens',
      description: 'High-fidelity onboarding UI.',
      status: 'TODO',
      type: 'DESIGN',
      priority: 'MEDIUM',
      assigneeId: 'user_alice',
      due_date: daysAgo(-10),
      updatedAt: now,
    },
    {
      id: 'task_lumen_1',
      projectId: 'proj_lumen',
      title: 'Define story arc',
      description: 'Outline key narrative sections.',
      status: 'DONE',
      type: 'PLANNING',
      priority: 'MEDIUM',
      assigneeId: 'user_alice',
      due_date: daysAgo(2),
      updatedAt: now,
    },
    {
      id: 'task_pulse_1',
      projectId: 'proj_pulsecare',
      title: 'Automate email triggers',
      description: 'Configure onboarding email sequence.',
      status: 'IN_PROGRESS',
      type: 'FEATURE',
      priority: 'HIGH',
      assigneeId: 'user_bob',
      due_date: daysAgo(-5),
      updatedAt: now,
    },
    {
      id: 'task_pulse_2',
      projectId: 'proj_pulsecare',
      title: 'FAQ content update',
      description: 'Refresh help articles and macros.',
      status: 'TODO',
      type: 'DOCS',
      priority: 'LOW',
      assigneeId: 'user_elliot',
      due_date: daysAgo(-12),
      updatedAt: now,
    },
    {
      id: 'task_summit_1',
      projectId: 'proj_summit',
      title: 'Tracking dashboard wireframes',
      description: 'Sketch initial flow for live tracking.',
      status: 'IN_PROGRESS',
      type: 'DESIGN',
      priority: 'HIGH',
      assigneeId: 'user_charles',
      due_date: daysAgo(-6),
      updatedAt: now,
    },
    {
      id: 'task_summit_2',
      projectId: 'proj_summit',
      title: 'Alerts microservice',
      description: 'Define webhook events and payloads.',
      status: 'TODO',
      type: 'FEATURE',
      priority: 'MEDIUM',
      assigneeId: 'user_farah',
      due_date: daysAgo(-14),
      updatedAt: now,
    },
    {
      id: 'task_nova_1',
      projectId: 'proj_nova',
      title: 'Offline mode prototype',
      description: 'Document fallback flows.',
      status: 'ON_HOLD',
      type: 'RESEARCH',
      priority: 'MEDIUM',
      assigneeId: 'user_farah',
      due_date: daysAgo(-20),
      updatedAt: now,
    },
  ]);

  await db.insert(comments).values([
    {
      id: 'comment_aurora_1',
      taskId: 'task_aurora_1',
      userId: 'user_admin',
      content: 'Please include accessibility notes in the journey map.',
      createdAt: daysAgo(3),
    },
    {
      id: 'comment_pulse_1',
      taskId: 'task_pulse_1',
      userId: 'user_elliot',
      content: 'QA needs a staging flow before launch.',
      createdAt: daysAgo(2),
    },
    {
      id: 'comment_summit_1',
      taskId: 'task_summit_1',
      userId: 'user_charles',
      content: 'Wireframes draft ready for review.',
      createdAt: daysAgo(1),
    },
  ]);
};

run()
  .then(() => {
    console.log('Seed complete');
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
